/*

ALTER the system databases growth rates.
Review settings as these were put together in 2014

*/
SET NOCOUNT ON

USE [master]
GO
ALTER DATABASE [master] MODIFY FILE ( NAME = N'master', SIZE = 500MB , MAXSIZE = UNLIMITED , FILEGROWTH = 128MB )
GO
ALTER DATABASE [master] MODIFY FILE ( NAME = N'mastlog', SIZE = 250MB , MAXSIZE = UNLIMITED , FILEGROWTH = 64MB )
GO
USE [master]
GO
ALTER DATABASE [tempdb] MODIFY FILE ( NAME = N'tempdev', SIZE = 1024000KB , MAXSIZE = UNLIMITED , FILEGROWTH = 256MB )
GO
ALTER DATABASE [tempdb] MODIFY FILE ( NAME = N'templog', SIZE = 256000KB , MAXSIZE = UNLIMITED , FILEGROWTH = 128MB )
GO
USE [master]
GO
ALTER DATABASE [msdb] MODIFY FILE ( NAME = N'MSDBData', SIZE = 1024000KB , MAXSIZE = UNLIMITED , FILEGROWTH = 128MB )
GO
ALTER DATABASE [msdb] MODIFY FILE ( NAME = N'MSDBLog', SIZE = 256000KB , MAXSIZE = 256000KB , FILEGROWTH = 64MB )
GO
USE [master]
GO
ALTER DATABASE [model] MODIFY FILE ( NAME = N'modeldev', SIZE = 1024000KB , MAXSIZE = UNLIMITED , FILEGROWTH = 512MB )
GO
ALTER DATABASE [model] MODIFY FILE ( NAME = N'modellog', SIZE = 256000KB , MAXSIZE = UNLIMITED , FILEGROWTH = 64MB )
GO




